config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end
  end


  resource :profile, only: [:show, :edit, :update]

end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id           :bigint           not null, primary key
#  birthday     :date
#  gender       :integer
#  introduction :text
#  nickname     :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
  enum gender: { male: 0, female: 1, other: 2 }
  belongs_to :user
  has_one_attached :avatar
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_prof, only: [:edit, :update]

  def show
    @profile = current_user.profile
  end

  def edit
  end

  def update
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: 'プロフィールを更新しました。'
    else
      render :edit
    end
  end

  private
  def profile_params
    params.require(:profile).permit(
      :nickname,
      :introduction,
      :gender,
      :birthday,
      :subscribed,
      :avatar
    )
  end

  def set_prof
    @profile = current_user.profile || current_user.build_profile
  end

end

app/views/profiles/edit.html.haml
.container
  %ul
    - @profile.errors.full_messages.each do |message|
      %li= message
  %h2 Profile
  = form_with(model: @profile, url: profile_path, method: 'put', local: true, data: { turbo: false } ) do |f|
    %div
      = f.label :avatar, class: 'label'
    %div
      = f.file_field :avatar
    %div
      = f.label :nickname, class: 'label'
    %div
      = f.text_field :nickname, class: 'text_field'
    %div
      = f.label :introduction, class: 'label'
    %div
      = f.text_area :introduction, class: 'text_area'
    %div
      = f.label :gender, '性別', class: 'label'
    %div
      = f.select :gender, Profile.genders.keys, {}, { class: 'text' }
    %div
      = f.label :birthday, class: 'label'
    %div
      = f.date_field  :birthday, class: 'text'
    .actions
      = f.submit "保存", class: 'submit_btn'

app/views/profiles/show.html.haml
.container
  %h2 My Profile
  .profile_top
    %div= image_tag current_user.avatar_image
    .edit_prof
      = link_to image_tag('edit.png'), edit_profile_path
      .edit_text 編集する
  .label 名前
  %div.text_field= current_user.display_name
  .label 自己紹介
  %div.text_area= current_user.introduction
  .label 性別
  %div.text= current_user.gender
  .label 誕生日
  %div.text= current_user.birthday