config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end
  end


  resource :profile, only: [:show, :edit, :update]

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :bigint           not null, primary key
#  delivery    :date
#  description :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  board_id    :bigint
#  user_id     :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :board
  has_one_attached :eyecatch
  has_many :comments, dependent: :destroy
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_board, only: [:index, :new, :create, :destroy, :show]
  before_action :set_task, only: [:show, :destroy]
  before_action :set_edit_task, only: [:edit, :update]

  def index
    @tasks = @board.tasks.all
  end

  def new
    @task = @board.tasks.build
    @task.user = current_user
  end

  def create
    @task = @board.tasks.build(task_params)
    @task.user = current_user
    if @task.save
      redirect_to board_path(@board), notice: '保存できたよ'
    else
      puts @task.errors.full_messages #エラーメッセージをコンソールに出力
      Rails.logger.error(@task.errors.full_messages)
      flash.now[:error] = '保存に失敗しました' #失敗時にエラーメッセージを一時表示
      render :new
    end
  end

  def show
    @comments = @task.comments
  end

  def edit
  end

  def update
    puts "Updating task with params: #{task_params.inspect}"
    if @task.update(task_params)
      redirect_to board_task_path(@board, @task), notice: 'タスクを更新しました'
    else
      puts @task.errors.full_messages # エラーメッセージを出力
      flash.now[:error] = 'タスクの更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @task.destroy!
    redirect_to board_path(@board), notice: '削除に成功しました'
  end

  private

  def task_params
    params.require(:task).permit(
      :title,
      :description,
      :delivery,
      :eyecatch,
      :board_id
    )
  end

  def set_board
    @board = Board.find(params[:board_id])
  end

  def set_task
    begin
      @task = @board.tasks.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "指定されたタスクが見つかりませんでした"
      redirect_to board_path(@board)
    end
  end


  def set_edit_task
    @board = current_user.boards.find(params[:board_id])
    @task = @board.tasks.find(params[:id])
  end

end

app/views/tasks/_form.html.haml
.container
  %h2
    - if @task.persisted?
      タスクNo. #{@task.id}
    - else
      New Task

  = form_with(model: @task, 
              url: @task.persisted? ? board_task_path(@board, @task) : board_tasks_path(@board), 
              method: @task.persisted? ? :patch : :post, 
              local: true,
              multipart: true) do |f|
    = f.hidden_field :board_id, value: @board.id  # 追加
    .field
      = f.label :eyecatch, class: 'label'
      - if @task.eyecatch.attached?
        = image_tag url_for(@task.eyecatch), alt: "Current image"
      %div= f.file_field :eyecatch
    .field
      = f.label :title, class: 'label'
      = f.text_field :title, class: 'text_field'
    .field
      = f.label :description, class: 'label'
      = f.text_area :description, class: 'text_area'
    .field
      = f.label :delivery, class: 'label'
      = f.date_field :delivery, class: 'text'
    .actions
      = f.submit "Submit", class: 'submit_btn'

app/views/tasks/_index.html.haml
.container
  %h2 All Tasks
  - if tasks.present?
    = render 'commons/tasks', tasks: tasks, board: board
  - else
    %div.text_field まだタスクがありません
  %div.new_card
    = link_to '+ Add New Task', new_board_task_path(@board), class: 'new_task'

app/views/tasks/edit.html.haml
.container
  = render 'form', task: @task, board: @board

app/views/tasks/index.html.haml
%h2 タスク一覧
= render 'tasks/index',tasks: @tasks

app/views/tasks/new.html.haml
= render 'form', task: @task

app/views/tasks/show.html.haml
.container
  %h2 タスクNo.#{@task.id}
  .label Eyecatch
  .task_eyecatch
  - if @task.eyecatch.present?
    =image_tag @task.eyecatch, class: 'eyecatch'
  .field
    .label Title
    .text_field= @task.title
  .field
    .label Description
    .text_area= @task.description
  .field
    .label Delivery
    .text= @task.delivery
  
  .div
    %h2 コメント一覧
    - @comments.each do |comment|
      .comments
        %p= comment.description
    = link_to new_board_task_comment_path(@board, @task) do
      .submit_btn
        コメントを追加
  
  = link_to 'タスク一覧へ戻る', board_path(@board), class: 'label'