config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end
  end


  resource :profile, only: [:show, :edit, :update]

end

app/views/commons/_board.html.haml
.card
  .board_header
    .board_number ボードNo: #{board.id}
    - if user_signed_in? && current_user.boards.exists?(id: board.id)
      .dropdown_b
        = image_tag 'edit.png', class: 'dropbtn_b'
        .dropdown_contents_b.mini_b
          = link_to '編集する', edit_board_path(board)
          = link_to '削除する', board_path(board), data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' }
  = link_to board_path(id: board.id) do
    .board_title= board.title
    .board_desc= board.description
    .board_avatar= image_tag board.user.avatar_image

app/views/commons/_boards.html.haml
- boards.each do |board|
  = render 'commons/board', board: board

app/views/commons/_task.html.haml
.card
  .task_header
    .task_number タスクNo: #{task.id}
    - if user_signed_in? && current_user.tasks.exists?(id: task.id)
      .dropdown_t
        = image_tag 'edit.png', class: 'dropbtn_t'
        .dropdown_contents_t.mini_t
          = link_to '編集する', edit_board_task_path(board, task)
          = link_to '削除する', board_task_path(board, task), data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' }
  = link_to board_task_path(board, task) do
    .task_eyecatch
      - if task.eyecatch.present?
        =image_tag task.eyecatch, class: 'eyecatch'
    .task_title= task.title
    .task_desc= task.description

app/views/commons/_tasks.html.haml
- tasks.each do |task|
  = render 'commons/task', task: task, board: board