config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end
  end


  resource :profile, only: [:show, :edit, :update]

end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id          :bigint           not null, primary key
#  description :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord
  has_many :tasks
  belongs_to :user
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:edit, :update]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @boards = Board.all
  end

  def show
    @board = Board.find(params[:id])
    @tasks = @board.tasks
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to board_path(@board),notice: '保存できたよ' #保存成功時に詳細ページへ
    else
      puts @board.errors.full_messages #エラーメッセージをコンソールに出力
      flash.now[:error] = '保存に失敗しました' #失敗時にエラーメッセージを一時表示
      render :new #フォームを再表示(入力データは保持)
    end
  end

  def edit
    #set_board
  end

  def update
    #set_board
    if @board.update(board_params)
      redirect_to board_path(@board), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    board = current_user.boards.find(params[:id])
    board.destroy!
    redirect_to root_path, notice: '削除に成功しました'
  end

  private
  def board_params
    params.require(:board).permit(:title, :description)
  end

  def set_board
    @board = current_user.boards.find(params[:id])
  end

end

app/views/boards/_form.html.haml
.container#board
  %h2
    - if board.id.present?
      ボードNo. #{board.id}
    - else
      New Board

  = form_with(model: board, url: boards_path, method: 'post', local: true, data: { turbo: false } ) do |f|
    .field
      = f.label :title, class: 'label'
      = f.text_field :title, class: 'text_field'
    .field
      = f.label :description, class: 'label'
      = f.text_area :description, class: 'text_area'
    .actions
      = f.submit "Submit" ,class: 'submit_btn'

app/views/boards/edit.html.haml
= render 'form',board: @board

app/views/boards/index.html.haml
.container
  %h2 All Boards
  = render 'commons/boards', boards: @boards
  %div.new_card
    = link_to '+ Add New Board', new_board_path, class: 'new_board'

app/views/boards/new.html.haml
= render 'form', board: @board

app/views/boards/show.html.haml
.container
  %h2 ボードNo.#{@board.id}
  .field
    .label Author
    =image_tag @board.user.avatar_image
    %div #{@board.user.display_name} さん
  .field
    .label Title
    .text_field= @board.title
  .field
    .label Description
    .text_area= @board.description

  = render 'tasks/index', tasks: @tasks, board: @board